# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: testing
contracts:
  - name: DonationTracker
    handler: src/EventHandlers.ts
    events:
      - event: CampaignCreated(uint256 campaignId, address indexed creator)
      - event: CampaignEnded(uint256 campaignId, address creator, uint256 refundedFee)
      - event: DonationReceived(uint256 campaignId, address indexed donor, uint256 amount)
      - event: ProofUploaded(uint256 campaignId, uint256 withdrawalId, string proofUrl)
      - event: WithdrawalMade(uint256 campaignId, address indexed admin, uint256 amount)
networks:
  - id: 31
    rpc_config:
      url: https://public-node.testnet.rsk.co
    start_block: 0
    contracts:
      - name: DonationTracker
        address:
          - 0x1234567890123456789012345678901234567890
  - id: 1337
    rpc_config:
      url: https://rpc-quicknode-holesky.morphl2.io
    start_block: 0
    contracts:
      - name: DonationTracker
        address:
          - 0x9876543210987654321098765432109876543210
  - id: 11155111
    start_block: 0
    contracts:
      - name: DonationTracker
        address:
          - 0x7167C5B16dA69Ba6C0Ba00710Bd828B552486bD9
rollback_on_reorg: false
